travis:
  secure:
    BINSTAR_TOKEN: VTo/OmdARVH+rYeytX2Bfp5O0LWpT8i73g/CzgFh39ttuwPA+zYmHxYYBnFPvUB4ImBVYkgE97d3zgj2GnM2L2sPrC4KCrBFcRIRkjNdDU20Bpx5T7yOWMKzJMJIDY8DSbOKURkHxEjT4eIAQ9vCwmvbS+iHu1+0/KiY+GoTABfcibvuBhLD9OEkzIztLIeBTpsCWseWSoYfqRXMMMy6qY68uK35WfO8gJY7NhB0qx7cwGBJ21sBAW+tC+RjW0nRoitrd6PCIlyHZOnDW5F3QMubHWoyKkyKswZHRipWLtQ9Kxb0KurSA6BHgDtDZi+uIW7va5feOrl50ZlaMv1FSBRhMssgmYfCYVKYjtIUpQzPoGWsw9b9iSCDt5BdBUEIS7hKWZcfbsMjbCbBiP9IlJt8e1r3pAlHFCVgNLjhTJEytsIsXN7Jfmq8TW3OfUyzqndHtcHSAs5n+jS6QRKUFAHD/Ylhg8QYRYw7eSdvKMS6Kx397S7kLrUfLYNYcxvzB7Z6SdGu+/Tm+7yXRpJjfENEhsEyePc2Ul0ORM5wRQn9aRjS7Z1q/kU0celf7S7fwnlNWoODVx69fzu8YuuvwItbMp+QL9F9i+XpGPdQaOodf+CFwGa+olEVWFaea7UgvRWtdt2E8+HPrq58Su3pO52fNN3+wgPQ6w7VAPg4ICg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
